### ISSUE TITLE
Problem on publish task

### ISSUE THREAD

**Issue by felipe-allmeida** [juunas11/azure-pipelines-aad-b2c-policy-tasks#1]
Hello!

I'm trying to use your lib to publish my policies and i'm receiving the following error on the publish task:
![image](https://user-images.githubusercontent.com/62676728/131717335-2c8a786f-b32b-481f-9a77-b62ca876d5a2.png)

Here is my pipeline:
```yml
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - assets/policies/dev/nutricionista/*
    exclude:
    - src/*
    - .azure/*

pool:
  vmImage: 'windows-latest'

variables:
- name: 'ps1FilePath'
  value: 'assets/scripts/DeployToB2c.ps1'
- name: 'policiesPath'
  value: './assets/policies/dev/nutricionista'

- group: dietbox-env-vars-b2c-nutricionista-dev

steps:
- task: b2c-policy-build@1
  displayName: Build policies
  inputs:
    environment: "Development"
    inputFolder: "$(Build.Repository.LocalPath)/$(policiesPath)"
    outputFolder: "$(Build.ArtifactStagingDirectory)/policies"

- task: b2c-policy-publish@1
  displayName: Publish policies
  inputs:
    inputFolder: "$(Build.ArtifactStagingDirectory)/policies"
    authority: "https://login.microsoftonline.com/$(tenantId)"
    clientId: "$(clientId)"
    clientSecret: "$(clientSecret)"
```
